### ISSUE TITLE
`episodes` を `animedb.yml` から分離する

### ISSUE THREAD

**Issue by builtinnya** [anilogia/animedb#46]
**※ PR #45 がマージされてから取り組むこと**

## 背景

ランダム文字列を識別子とする変更（issue #39，PR #45）に伴い，作品の基本情報以外のデータ（各話情報やスタッフ，キャラクターなど）を，識別子を用いて関連付けられるようになった（厳密にいえば変更前も識別名を用いて可能だったが，識別名には変更可能性が存在するため，難しかった）．
各話情報は既に一部のアニメについて入力されている（refs: #6，#10，#43）が，その数は作品よりオーダーが大きい．そのため，見通しが悪くなったり，スクリプトでの処理時間が余計に長くなったりして，編集作業に支障をきたしている．

## 問題

- 各話情報が膨大であり，編集作業の効率が低下している

## 解決方法案

スタッフやキャラクターなどのデータを将来的に追加することも見据えて，各話情報（`episodes`）を `animedb.yml` から分離する．つまり，各話情報は例えば `episodes.yml` ファイルに移される．
`animedb.yml` を `animes.yml` にファイル名を変更した方が命名的に一貫しているが，変更するかどうかは考えどころ．

`episodes.yml` の構造は以下のようになる．各話情報にも作品と同様に `id` を用意する予定．

```yaml
Z5bwa8ArLg5: # 作品の id
  - id: mR22RyrHEuU # 各話情報そのものの id
    prefix: 第1話
    title: チビッ子魔女がやってきた No.1
    literal_title: 第1話 チビッ子魔女がやってきた No.1
    annict_id: 78126
  - ...
```
