### ISSUE TITLE
各話情報を入力する（構造・方針）

### ISSUE THREAD

**Issue by builtinnya** [anilogia/animedb#6]
アニメの各話情報（エピソード）を入力する．
## 構造

`episodes` キーに配列として表す．
各話ごとのスタッフ情報など，他にも様々な情報が考えられるが，一旦以下の例にあるように最低限の情報だけ記録する（それでも今記録されている全てのアニメを網羅するのは大変）．

``` yaml
episodes:
  - prefix: "第1話" # エピソードの位置を指定する（と思われる）文字列
    title: "16の星と月が巡る日" # 基本的には literal_title から prefix を抜いたもの
    literal_title: "第1話 16の星と月が巡る日" # エピソードの無加工のタイトル
    ruby: "ジュウロクノホシトツキガメグルヒ" # title のヨミガナ
    started_at: "2000/04/20 18:30" # （最速）放送開始日時
    ended_at: "2000/04/20 19:00" #（最速）放送終了日時
```
## 入力方針

まずは[メディア芸術データベース](https://mediaarts-db.jp/)から各話情報を取得して加筆・修正を行っていく．
網羅率や正確性は高くないと思われるので，その他の起点になり得るデータベースを活用して情報を埋めていく．
但し，メディア芸術データベース以外を利用する場合は，名寄せの問題が難しい．
## 起点になり得る他データベース
- [メディア芸術データベース](https://mediaarts-db.jp/)
  - 大幅に加筆・修正してるといえど，本データベースはメディア芸術データベースを元にしているため，名寄せの手間がかからない
- [Annict](https://annict.com/)
  - 網羅率高そう
  - API があるため取得しやすい
  - 名寄せが大変そう
- [しょぼいカレンダー](http://cal.syoboi.jp/)
  - [Annict](https://annict.com/) のデータ元
- [aniDB](http://anidb.net/)
  - 英語だが日本語表記も取得できる
- [AnimeNewsNetwork](http://www.animenewsnetwork.com/encyclopedia/anime.php)
  - 英語だが日本語表記も取得できる
