### ISSUE TITLE
CSVファイルの誤記について

### ISSUE THREAD

**Issue by coexe** [anilogia/animedb#60]
CSVファイルで、この行だけ題名がダブルクォートで囲まれており、処理系によっては題名の末尾のカンマ部分が正しく解釈できない可能性がありますのでご報告します

ANS000808400,劇場,,PzJjXWzLMU2,"科学忍者隊ガッチャマン 火の鳥対火喰い竜,",,カガクニンジャタイガッチャマン ヒノトリタイヒクイリュウ,1973,7,28,,,,東宝,-,,http://mediaarts-db.jp/an/anime_series/12795,,

**Comment by builtinnya** [comment]
題名の末尾のカンマは，CSV を吐き出すときのエラーではなく，元データに含まれているものですね．
修正いたします．

```yaml
- madb_id: ANS000808400
  medium: 劇場
  duplicated:
  id: PzJjXWzLMU2
  title: 科学忍者隊ガッチャマン 火の鳥対火喰い竜,
  suffix:
  ruby: カガクニンジャタイガッチャマン ヒノトリタイヒクイリュウ
  started_year: 1973
  started_month: 7
  started_day: 28
  ended_year:
  ended_month:
  ended_day:
  broadcast: 東宝
  author: '-'
  original_title:
  madb_uri: http://mediaarts-db.jp/an/anime_series/12795
  official_uri:
  memo:
```
